# Generated by Django 5.0.6 on 2024-07-29 15:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userdetail",
            name="id",
        ),
        migrations.AddField(
            model_name="userdetail",
            name="userId",
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
    ]
