# Generated by Django 5.0.6 on 2024-07-29 15:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_remove_userdetail_id_userdetail_userid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userdetail",
            name="userId",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
