# Generated by Django 5.0.6 on 2024-07-31 12:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_alter_userdetail_userid"),
    ]

    operations = [
        migrations.CreateModel(
            name="StudentDetails",
            fields=[
                ("studentId", models.AutoField(primary_key=True, serialize=False)),
                ("firstname", models.CharField(max_length=40)),
                ("lastname", models.CharField(max_length=40)),
                ("gender", models.CharField(max_length=7)),
                ("email", models.EmailField(max_length=80)),
                ("dob", models.DateField()),
                ("faculty", models.CharField(max_length=80)),
                ("section", models.CharField(max_length=15)),
            ],
        ),
    ]
