# Generated by Django 5.0.6 on 2024-07-31 13:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_alter_studentdetails_firstname_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studentdetails",
            name="dob",
            field=models.CharField(max_length=80),
        ),
    ]
