# Generated by Django 5.0.6 on 2024-07-31 13:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0006_alter_studentdetails_dob"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studentdetails",
            name="email",
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name="studentdetails",
            name="firstname",
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name="studentdetails",
            name="lastname",
            field=models.CharField(max_length=40),
        ),
    ]
