# Generated by Django 5.0.6 on 2024-07-31 13:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0007_alter_studentdetails_email_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studentdetails",
            name="gender",
            field=models.CharField(max_length=20),
        ),
    ]
